/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LocationResolution } from './location-resolution';
// May contain unused imports in some cases
// @ts-ignore
import type { MeasurementResolution } from './measurement-resolution';

/**
 * 
 * @export
 * @interface PolicyDto
 */
export interface PolicyDto {
    /**
     * 
     * @type {string}
     * @memberof PolicyDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PolicyDto
     */
    'name': string;
    /**
     * 
     * @type {MeasurementResolution}
     * @memberof PolicyDto
     */
    'measurementResolution': MeasurementResolution;
    /**
     * 
     * @type {LocationResolution}
     * @memberof PolicyDto
     */
    'locationResolution': LocationResolution;
    /**
     * 
     * @type {number}
     * @memberof PolicyDto
     */
    'price': number;
}



