/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MeasurementRawDto } from '../models';
// @ts-ignore
import type { ProblemDetails } from '../models';
/**
 * MeasurementApi - axios parameter creator
 * @export
 */
export const MeasurementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} smartMeterId 
         * @param {string} startAt 
         * @param {string} endAt 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMeasurements: async (smartMeterId: string, startAt: string, endAt: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'smartMeterId' is not null or undefined
            assertParamExists('getMeasurements', 'smartMeterId', smartMeterId)
            // verify required parameter 'startAt' is not null or undefined
            assertParamExists('getMeasurements', 'startAt', startAt)
            // verify required parameter 'endAt' is not null or undefined
            assertParamExists('getMeasurements', 'endAt', endAt)
            const localVarPath = `/api/measurements`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (smartMeterId !== undefined) {
                localVarQueryParameter['smartMeterId'] = smartMeterId;
            }

            if (startAt !== undefined) {
                localVarQueryParameter['startAt'] = (startAt as any instanceof Date) ?
                    (startAt as any).toISOString() :
                    startAt;
            }

            if (endAt !== undefined) {
                localVarQueryParameter['endAt'] = (endAt as any instanceof Date) ?
                    (endAt as any).toISOString() :
                    endAt;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MeasurementApi - functional programming interface
 * @export
 */
export const MeasurementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MeasurementApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} smartMeterId 
         * @param {string} startAt 
         * @param {string} endAt 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMeasurements(smartMeterId: string, startAt: string, endAt: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MeasurementRawDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMeasurements(smartMeterId, startAt, endAt, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MeasurementApi.getMeasurements']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MeasurementApi - factory interface
 * @export
 */
export const MeasurementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MeasurementApiFp(configuration)
    return {
        /**
         * 
         * @param {string} smartMeterId 
         * @param {string} startAt 
         * @param {string} endAt 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMeasurements(smartMeterId: string, startAt: string, endAt: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<MeasurementRawDto>> {
            return localVarFp.getMeasurements(smartMeterId, startAt, endAt, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MeasurementApi - object-oriented interface
 * @export
 * @class MeasurementApi
 * @extends {BaseAPI}
 */
export class MeasurementApi extends BaseAPI {
    /**
     * 
     * @param {string} smartMeterId 
     * @param {string} startAt 
     * @param {string} endAt 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MeasurementApi
     */
    public getMeasurements(smartMeterId: string, startAt: string, endAt: string, options?: RawAxiosRequestConfig) {
        return MeasurementApiFp(this.configuration).getMeasurements(smartMeterId, startAt, endAt, options).then((request) => request(this.axios, this.basePath));
    }
}

