/* tslint:disable */
/* eslint-disable */
/**
 * SMAIAX Backend API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PolicyDto } from '../models';
// @ts-ignore
import type { PolicyRequestCreateDto } from '../models';
// @ts-ignore
import type { ProblemDetails } from '../models';
/**
 * PolicyrequestApi - axios parameter creator
 * @export
 */
export const PolicyrequestApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {PolicyRequestCreateDto} policyRequestCreateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPolicyRequest: async (policyRequestCreateDto: PolicyRequestCreateDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'policyRequestCreateDto' is not null or undefined
            assertParamExists('createPolicyRequest', 'policyRequestCreateDto', policyRequestCreateDto)
            const localVarPath = `/api/policyRequests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(policyRequestCreateDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchingPolicies: async (id: string, body: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getMatchingPolicies', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('getMatchingPolicies', 'body', body)
            const localVarPath = `/api/policyRequests/{id}/policies`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PolicyrequestApi - functional programming interface
 * @export
 */
export const PolicyrequestApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PolicyrequestApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {PolicyRequestCreateDto} policyRequestCreateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPolicyRequest(policyRequestCreateDto: PolicyRequestCreateDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PolicyDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPolicyRequest(policyRequestCreateDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PolicyrequestApi.createPolicyRequest']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMatchingPolicies(id: string, body: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PolicyDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMatchingPolicies(id, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PolicyrequestApi.getMatchingPolicies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PolicyrequestApi - factory interface
 * @export
 */
export const PolicyrequestApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PolicyrequestApiFp(configuration)
    return {
        /**
         * 
         * @param {PolicyRequestCreateDto} policyRequestCreateDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPolicyRequest(policyRequestCreateDto: PolicyRequestCreateDto, options?: RawAxiosRequestConfig): AxiosPromise<Array<PolicyDto>> {
            return localVarFp.createPolicyRequest(policyRequestCreateDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {string} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMatchingPolicies(id: string, body: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<PolicyDto>> {
            return localVarFp.getMatchingPolicies(id, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PolicyrequestApi - object-oriented interface
 * @export
 * @class PolicyrequestApi
 * @extends {BaseAPI}
 */
export class PolicyrequestApi extends BaseAPI {
    /**
     * 
     * @param {PolicyRequestCreateDto} policyRequestCreateDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PolicyrequestApi
     */
    public createPolicyRequest(policyRequestCreateDto: PolicyRequestCreateDto, options?: RawAxiosRequestConfig) {
        return PolicyrequestApiFp(this.configuration).createPolicyRequest(policyRequestCreateDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {string} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PolicyrequestApi
     */
    public getMatchingPolicies(id: string, body: string, options?: RawAxiosRequestConfig) {
        return PolicyrequestApiFp(this.configuration).getMatchingPolicies(id, body, options).then((request) => request(this.axios, this.basePath));
    }
}

